# Generated by Django 5.1.3 on 2025-03-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_list", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
