# Generated by Django 5.1.3 on 2025-02-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="catalog/images",
                verbose_name="изображение",
            ),
        ),
    ]
