# Generated by Django 5.1.3 on 2025-02-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(
                default=True, verbose_name="Доступность в каталоге"
            ),
        ),
    ]
